name: run tests
run-name: ${{ github.actor }} is running tests...
on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v3
          with:
            python-version: '3.x'
        - run: pip install invoke
        - run: invoke setup --dev
        - run: invoke test
